apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-nginx-deployment
  labels:
    app: app1-nginx # name of the depoyment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-nginx # this should be same as the name of the pod
  template:
    metadata:
      labels:
        app: app1-nginx # name of the pod
    spec:
      containers:
        - name: app1-demo-nginx #  name of the container
          image: azrondevops.azurecr.io/app1/nginx-manual # name of the conatiner repository in acr
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-loadbalancer-service
  labels:
    app: app1-nginx # name of the pod where this load balancer will direct traffic
spec:
  type: LoadBalancer
  selector:
    app: app1-nginx
  ports:
    - port: 80
      targetPort: 80
